### ISSUE TITLE
Проверка ДЗ №5 "Posts"

### ISSUE THREAD

**Issue by lowerKamaCase** [lowerKamaCase/CreatePosts#1]
https://lowerkamacase.github.io/CreatePosts/

Есть косяк в коде. Лайки и дизлайки для всех постов кроме первого не кликаются.
Думаю, это связано с тем, что в 165 и 178 строках app.js я получаю тот же первый элемент.
Но как по другому onclick повесить на все остальные кнопки, кроме как через querySelector, не знаю.
Подскажите, как решить это?

**Comment by coursar** [comment]
См. #7.
