### ISSUE TITLE
Не предзаполнять поля

### ISSUE THREAD

**Issue by coursar** [lowerKamaCase/CreatePosts#2]
https://github.com/lowerKamaCase/CreatePosts/blob/1608c69193350751128ed853996a4bf8cfa90618/app.js#L25-L33

Попробуйте сделать расчёт id автоматически, а кол-во лайков/дизлайков должно быть равным 0 при создании.

**Comment by lowerKamaCase** [comment]
Расчёт id происходит автоматически. Первый 0, второй - 1, и т.д.
