### ISSUE TITLE
У вас в HTML уже есть эти элементы

### ISSUE THREAD

**Issue by coursar** [lowerKamaCase/CreatePosts#5]
https://github.com/lowerKamaCase/CreatePosts/blob/1608c69193350751128ed853996a4bf8cfa90618/app.js#L87-L90

Включая элемент с `id=root`, зачем вы их ещё добавляете при каждом создании поста? Вам, фактически, нужно добавлять только `card`.

**Comment by lowerKamaCase** [comment]
Удалил лишнее
