### ISSUE TITLE
Попробуйте вынести в отдельную функцию/функции

### ISSUE THREAD

**Issue by coursar** [lowerKamaCase/CreatePosts#6]
https://github.com/lowerKamaCase/CreatePosts/blob/1608c69193350751128ed853996a4bf8cfa90618/app.js#L85-L161

**Comment by lowerKamaCase** [comment]
вынес в returnPost()
Остается вопрос - как найти создаваемые посты в DOM'е и повесить на них обработчик (лайки и дизлайки)?
